class StillNotFound(Exception):
    pass

class Finished(Exception):
    pass
